### ISSUE TITLE
alerts with errors blocking website

### ISSUE THREAD

**Issue by razbakov** [kt474/tailwind-converter#14]
**How to reproduce:**
Open website https://tailwindconverter.app/

**Expected result**
Page is loaded

**Actual result**
Alerts is shown. Clicking on "OK" another alert is shown. And it happens a lot of times before you can access the website.
Example of alert: `Invalid Color: Error: "var(--bs-body-color)" is not a valid color`

**Comment by kt474** [comment]
Thanks for reporting this - the alert has been replaced with a `console.error`. Fixed in https://github.com/kt474/tailwind-converter/commit/c3fe08ed12733c51941ebf07c8d082348bb1ae44
